name: pitest
on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
        architecture: [ 'x64' ]
    name: Mutation Testing with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    services:
      # Label used to access the service container
      nacos:
        image: nacos/nacos-server:1.3.2
        env:
          MODE: standalone
        ports:
          - 8848:8848
        options: >-
          --health-cmd "curl http://127.0.0.1:8848/nacos"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: ${{ matrix.architecture }}

      - uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn package -DskipTests
        env:
          NACOS_REGISTRY_SERVER_ADDR: 127.0.0.1:8848
          HZ_APPLICATION_NAME: HZ_APP

      - name: Run Mutation Testing
        run: mvn -Ppitest org.pitest:pitest-maven:mutationCoverage
        env:
          NACOS_REGISTRY_SERVER_ADDR_TEST: 127.0.0.1:8848
          HZ_APPLICATION_NAME: HZ_APP

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/pit-reports/*/
          destination_dir: pitest

